// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Match struct {
	ID        int32         `json:"id"`
	PlayerXID sql.NullInt32 `json:"playerXId"`
	PlayerYID sql.NullInt32 `json:"playerYId"`
	WinnerID  sql.NullInt32 `json:"winnerId"`
	PlayedAt  sql.NullTime  `json:"playedAt"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"passwordHash"`
	CreatedAt    sql.NullTime `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
}
