// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Match struct {
	ID        uuid.UUID `json:"id"`
	PlayerXID uuid.UUID `json:"player_x_id"`
	PlayerYID uuid.UUID `json:"player_y_id"`
	WinnerID  uuid.UUID `json:"winner_id"`
	PlayedAt  time.Time `json:"played_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
