// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserMatches(ctx context.Context, winnerID sql.NullInt32) ([]GetUserMatchesRow, error)
	GetUserStats(ctx context.Context, winnerID sql.NullInt32) (GetUserStatsRow, error)
}

var _ Querier = (*Queries)(nil)
