// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserMatches(ctx context.Context, winnerID uuid.UUID) ([]GetUserMatchesRow, error)
	GetUserStats(ctx context.Context, winnerID uuid.UUID) (GetUserStatsRow, error)
}

var _ Querier = (*Queries)(nil)
